<?xml version="1.0"?>
<robot name="diff_robot" xmlns:xacro="http://www.ros.org/wiki/xacro"> 

<!-- Definovanie materiálov -->
<material name="Black">
	<color rgba="0.0 0.0 0.0 1.0"/>
</material>

<material name="Blue">
	<color rgba="0.0 0.0 0.8 1.0"/>
</material>

<material name="Red">
	<color rgba="0.8 0.0 0.0 1.0"/>
</material>

<material name="White">
	<color rgba="1.0 1.0 1.0 1.0"/>
</material>


<!-- zadefinovanie premených -->
<xacro:property name="base_radius" value="0.2"/>
<xacro:property name="base_length" value="0.03"/>
<xacro:property name="base_mass"   value="5"/>


<xacro:property name="PI_2"         value="1.57079632679"/>
<xacro:property name="wheel_radius" value="0.075"/>
<xacro:property name="wheel_length" value="0.02"/>
<xacro:property name="wheel_mass"   value="1.5"/>


<xacro:property name="caster_radius" value="0.03"/>
<xacro:property name="caster_mass"   value="0.2"/>

<xacro:property name="sensor_size" value="0.05"/> 

<xacro:property name="camera_size" value="0.05"/> 

<!-- Makrá pre výpočet zotrvačnosti válca a gule -->
<xacro:macro name="cylinder_inertia"        params="m r h">
	<inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
                  iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
                  izz="${m*r*r/2}" /> 
</xacro:macro>
<xacro:macro name="sphere_inertia"   params="m r">
	<inertia  ixx="${2*m*r*r/5}" ixy = "0" ixz = "0"
                  iyy="${2*m*r*r/5}" iyz = "0"
                  izz="${2*m*r*r/5}" /> 
</xacro:macro>
  
<!-- ZOZNAM LINKOV -->

<!-- nastavenie vlastností stopy základne -->
 <link name="base_footprint"> 
 <visual>
 <origin rpy="0 0 0" xyz="0 0 0"/>
 <geometry>
 <box size="0.001 0.001 0.001"/>
 </geometry>
 </visual>
 </link>

<!-- nastavenie vlastností základne -->
<link name="base_link">
	<visual>
		<geometry>
			<cylinder length="${base_length}" radius="${base_radius}"/>
		</geometry>

		<origin rpy="0 0 0" xyz="0 0 0"/>   
		<material name="Blue"/>		     	
	</visual>
	<collision>
		<geometry>
			<cylinder length="${base_length}" radius="${base_radius}"/>
		</geometry>
		<origin rpy="0 0 0" xyz="0 0 0"/> 
	</collision>
	<inertial>
		<mass value="${base_mass}"/>
		<origin xyz="0 0 0"/>
		<cylinder_inertia  m="${base_mass}" r="${base_radius}" h="${base_length}" />
	</inertial>
</link>

<!-- nastavenie vlastností ľavého kolesa -->
<link name="left_wheel_link">
	<visual>
		<geometry>
			<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
		</geometry>

		<origin rpy="${PI_2} 0 0" xyz="0 0 0"/>
		<material name="Black"/>
	</visual>
	<collision>
		<geometry>
			<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
		</geometry>
		<origin rpy="${PI_2} 0 0" xyz="0 0 0"/>  
	</collision>
	<inertial>
		<mass value="${wheel_mass}"/>  
		<origin xyz="0 0 0"/>
		<cylinder_inertia  m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}" />
	</inertial>
</link>

<!-- nastavenie vlastností pravého kolesa -->
<link name="right_wheel_link">
	<visual>
		<geometry>
			<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
		</geometry>

		<origin rpy="${PI_2} 0 0" xyz="0 0 0"/>
		<material name="Black"/>
	</visual>
	<collision>
		<geometry>
			<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
		</geometry>
		<origin rpy="${PI_2} 0 0" xyz="0 0 0"/>  
	</collision>
	<inertial>
		<mass value="${wheel_mass}"/>  
		<origin xyz="0 0 0"/>
		<cylinder_inertia  m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}" />
	</inertial>
</link>

<!-- nastavenie vlastností predného pomocného kolieska -->
<link name="front_caster_link">
	<visual>
		<geometry>
			<sphere radius="${caster_radius}"/>
		</geometry>
		<origin rpy="${-PI_2} 3.1416 0" xyz="0 0 0"/> 
		<material name="Black"/>
	</visual>
	<collision>
		<geometry>
			<sphere radius="${caster_radius}"/>
		</geometry>
		<origin rpy="${-PI_2} 3.1416 0" xyz="0 0 0"/> 
	</collision>
	<inertial>
		<mass value="${caster_mass}"/>
		<origin xyz="0 0 0"/>
		<sphere_inertia  m="${caster_mass}" r="${caster_radius}" />
	</inertial>
</link>

<!-- nastavenie vlastností zadného pomocného kolieska -->
<link name="back_caster_link">
	<visual>
		<geometry>
			<sphere radius="${caster_radius}"/>
		</geometry>
		<origin rpy="${-PI_2} 3.1416 0" xyz="0 0 0"/>
		<material name="Black"/>
	</visual>
	<collision>
		<geometry>
			<sphere radius="${caster_radius}"/>
		</geometry>
		<origin rpy="${-PI_2} 3.1416 0" xyz="0 0 0"/> 
	</collision>
	<inertial>
		<mass value="${caster_mass}"/>
		<origin xyz="0 0 0"/>
		<sphere_inertia  m="${caster_mass}" r="${caster_radius}" />
	</inertial>
	
	
</link>

<!-- nastavenie vlastností laserového senzora -->
<link name="hokuyo_link">
	<visual>
		<geometry>
			<box size="${sensor_size} ${sensor_size} ${sensor_size}"/>
		</geometry>
		<origin xyz="0 0 0" rpy="0 0 0" />
		<maretial name="Red"/>
	</visual>
	<collision>
		<geometry>
			<box size="${sensor_size} ${sensor_size} ${sensor_size}"/>
		</geometry>
		<origin xyz="0 0 0" rpy="0 0 0" />
	</collision>
	<material name="Red"/>

</link>
<!-- nastavenie vlastností kamery-->
<link name="left_camera_frame">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${camera_size} ${camera_size} ${camera_size}"/> 
      </geometry>
      <material name="White"/>
    </visual>
</link>
<!-- JOINT LIST-->

<!-- nastavenie vlastností kĺbu,ktorý sa nachádza medzi stopou základne a základňou-->
<joint name="base_footprint_joint" type="fixed"> <!--FIXED- kĺb sa neotáča -->
 <origin rpy="0 0 0" xyz="0 0 0"/>
 <parent link="base_footprint"/>
 <child link="base_link"/>
 </joint>

<!-- nastavenie vlastností kĺbu,ktorý sa nachádza medzi ľavým kolesom a základňou-->
<joint name="left_wheel_joint" type="continuous">  <!--CONTINUOUS- pre neobmedzené otáčanie -->
	<parent link="base_link"/>
	<child link="left_wheel_link"/>
	<origin rpy="0 0 0" xyz="0 -0.2 0"/>                            
	<axis xyz="0 1 0" rpy="0  0"/>                          
	<limit effort="100" velocity="100" />  
	<dynamics damping="0.0" friction="0.0"/>    
</joint>

<!-- nastavenie vlastností kĺbu,ktorý sa nachádza medzi pravým kolesom a základňou-->
<joint name="right_wheel_joint" type="continuous">
	<parent link="base_link"/>
	<child link="right_wheel_link"/>
	<origin rpy="0 0 0" xyz="0 0.2 0"/>
	<axis  xyz="0 1 0" rpy="0  0"/>
        <limit effort="100" velocity="100" /> 
	<dynamics damping="0.0" friction="0.0"/>
</joint>

<!-- nastavenie vlastností kĺbu,ktorý sa nachádza medzi predným kolieskom a základňou-->
<joint name="front_caster_joint" type="fixed">
	<parent link="base_link"/>
	<child link="front_caster_link"/>
	<origin rpy="0 0 0" xyz="0.15 0 -0.044"  />   
</joint>

<!-- nastavenie vlastností kĺbu,ktorý sa nachádza medzi zadným kolieskom a základňou-->
<joint name="back_caster_joint" type="fixed">
	<parent link="base_link"/>
	<child link="back_caster_link"/>
	<origin rpy="0 0 0" xyz="-0.15 0 -0.044"  />   
</joint>

<!-- nastavenie vlastností kĺbu,ktorý sa nachádza medzi laserovým senzorom a základňou-->
<joint name="hokuyo_joint" type="fixed">
	<parent link="base_link"/>
	<child link="hokuyo_link" />
        <origin xyz="${base_radius-sensor_size/2} 0 ${base_length/2+sensor_size/2}" rpy="0 0 0" />
</joint>

<!-- nastavenie vlastností kĺbu,ktorý sa nachádza medzi kamerou a základňou-->
<joint name="left_camera_frame_joint" type="fixed">
    <origin xyz="${-base_radius+camera_size/2} 0 ${base_length+camera_size/4}" rpy="0 0 3.14" />
    <parent link="base_link"/>
    <child link="left_camera_frame" />
</joint>

<!-- GAZEBO LIST-->

<!-- nastavenie vlastností pre načítanie stopy základne v Gazebe-->
<gazebo reference="base_footprint">
    <turnGravityOff>false</turnGravityOff>
</gazebo>

<!-- nastavenie vlastností pre načítanie základne v Gazebe-->
<gazebo reference="base_link">
	<turnGravityOff>false</turnGravityOff>
	<material>Gazebo/Blue</material>
	
</gazebo>

<!-- nastavenie vlastností pre načítanie ľavého kolesa v Gazebe-->
<gazebo reference="left_wheel_link">
	<turnGravityOff>false</turnGravityOff>
	<material>Gazebo/Black</material>
	<mu1 value="1.0"/>
	<mu2 value="1.0"/>
	<kp value="10000000.0"/>
	<kd value="1.0"/>
	<fdir1 value="1 0 0"/>
	
</gazebo>

<!-- nastavenie vlastností pre načítanie pravého kolesa v Gazebe-->
<gazebo reference="right_wheel_link">
	<turnGravityOff>false</turnGravityOff>
	<material>Gazebo/Black</material>
	<mu1 value="1.0"/>
	<mu2 value="1.0"/>
	<kp value="10000000.0"/>
	<kd value="1.0"/>
	<fdir1 value="1 0 0"/>	
</gazebo>

<!-- nastavenie vlastností pre načítanie predného kolieska v Gazebe-->
<gazebo reference="front_caster_link">
	<turnGravityOff>false</turnGravityOff>
	<material>Gazebo/Black</material>
</gazebo>

<!-- nastavenie vlastností pre načítanie zadného kolieska v Gazebe-->
<gazebo reference="back_caster_link">
	<turnGravityOff>false</turnGravityOff>
	<material>Gazebo/Black</material>
</gazebo>

<!-- nastavenie vlastností pre načítanie senzora a jeho pluginu v Gazebe-->
<gazebo reference="hokuyo_link">
    <sensor type="ray" name="head_hokuyo_sensor">
       <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>40</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-1.57079632679</min_angle>
            <max_angle>1.57079632679</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>10.0</max>
          <resolution>0.001</resolution>
        </range>       
      </ray>
      <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
        <topicName>/scan</topicName>
        <frameName>hokuyo_link</frameName>
      </plugin>
    </sensor>
    <material>Gazebo/Red</material>
</gazebo>

<!-- nastavenie vlastností pre načítanie kamery a jeho pluginu v Gazebe-->
<gazebo reference="left_camera_frame">
    <sensor type="multicamera" name="stereo_camera">
      <update_rate>30.0</update_rate>
      <camera name="left">
        <material>Gazebo/White</material>
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>800</width>
          <height>800</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <camera name="right">
        <pose>0 -0.07 0 0 0 0</pose>
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>800</width>
          <height>800</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <plugin name="stereo_camera_controller" filename="libgazebo_ros_multicamera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>0.0</updateRate>
        <cameraName>multisense_sl/camera</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>left_camera_optical_frame</frameName>
        <!--<rightFrameName>right_camera_optical_frame</rightFrameName>-->
        <hackBaseline>0.07</hackBaseline>
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
      </plugin>
    </sensor>
</gazebo>

<!-- nastavenie vlastností pre načítanie pluginu kontroléra diferenciálneho podvozku v Gazebe-->
<gazebo>
 <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
 <alwaysOn>true</alwaysOn>
 <rosDebugLevel>Debug</rosDebugLevel>
 <publishWheelTF>true</publishWheelTF>
 <robotNamespace>/</robotNamespace>
 <publishTf>1</publishTf>
 <publishWheelJointState>false</publishWheelJointState>
 <updateRate>50</updateRate>
 <leftJoint>left_wheel_joint</leftJoint>
 <rightJoint>right_wheel_joint</rightJoint>
 <wheelSeparation>${2*base_radius}</wheelSeparation>
 <wheelDiameter>${2*wheel_radius}</wheelDiameter>
 <broadcastTF>1</broadcastTF>
 <wheelTorque>18</wheelTorque>
 <wheelAcceleration>2.5</wheelAcceleration>
 <commandTopic>cmd_vel</commandTopic>
 <odometryFrame>odom</odometryFrame>
 <odometryTopic>odom</odometryTopic>
 <robotBaseFrame>base_footprint</robotBaseFrame>
 <legacyMode>true</legacyMode>
 <odometrysource>1</odometrysource>
 </plugin>
</gazebo>
<!-- LIST PREVODOV-->

<transmission name="left_wheel_joint_trans">
<type>transmission_interface/SimpleTransmission</type>
<joint name="left_wheel_joint">
<hardwareInterface>EffortJointInterface</hardwareInterface>
</joint>
<actuator name="left_wheel_joint_motor">
<hardwareInterface>EffortJointInterface</hardwareInterface>
<mechanicalReduction>1</mechanicalReduction>
</actuator>
</transmission>

<transmission name="right_wheel_joint_trans">
<type>transmission_interface/SimpleTransmission</type>
<joint name="right_wheel_joint">
<hardwareInterface>EffortJointInterface</hardwareInterface>
</joint>
<actuator name="right_wheel_joint_motor">
<hardwareInterface>EffortJointInterface</hardwareInterface>
<mechanicalReduction>1</mechanicalReduction>
</actuator>
</transmission>


</robot>
